### ISSUE TITLE
Review and cleannup the WIP commits

### ISSUE THREAD

**Issue by smortex** [smortex/freebsd-ports#1]
Can you please check the commits in the opensearch branch and tell me if you think something is wrong?

I would like to squash them as we move on

**Comment by smortex** [comment]
Maybe I should just open a PR and ask for approval there?  :roll_eyes:

**Comment by jurajlutter** [comment]
Yes, open a pull request.

**Comment by smortex** [comment]
Review is to be done in #3. Closing
