### ISSUE TITLE
Ask postmaster for an alias opensearch@ to contributors e-mail address.

### ISSUE THREAD

**Issue by smortex** [smortex/freebsd-ports#2]
Recipients of the alias:

* @smortex 
* @hackacad

**Comment by smortex** [comment]
@jurajlutter do you want to be part of an opensearch@ alias used as maintainer?

**Comment by jurajlutter** [comment]
Yes, sure.

**Comment by smortex** [comment]
Okay, I'll take care of it, thanks!

**Comment by smortex** [comment]
Done
